### PR TITLE
Automated LE certificate renewal

### PR DESCRIPTION
**Pull request by Tim-ofzo**
Tested successfully with `STANDALONE_CERT=1`, dns issue should work too.

### CODE REVIEW

**Comment by danb35** [comment]
The current setup already enables auto-renewal, and the acme.sh package is two months out of date.  I like using the packages in general, but given the pace of development on acme.sh I'm not sure that's the best way to go here.  What are your thoughts about the proposed changes?

**Comment by Tim-ofzo** [comment]
I didn't know it was already automated, my guess was it didn't work because every time I installed nextcloud it showed this in the terminal:
`[Tue Apr  3 00:33:34 CEST 2018] Installing from online archive.
[Tue Apr  3 00:33:34 CEST 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Tue Apr  3 00:33:35 CEST 2018] Extracting master.tar.gz
[Tue Apr  3 00:33:35 CEST 2018] Installing to /root/.acme.sh
[Tue Apr  3 00:33:35 CEST 2018] Installed to /root/.acme.sh/acme.sh
[Tue Apr  3 00:33:35 CEST 2018] Installing alias to '/root/.profile'
[Tue Apr  3 00:33:35 CEST 2018] OK, Close and reopen your terminal to start using acme.sh
[Tue Apr  3 00:33:35 CEST 2018] Installing alias to '/root/.cshrc'
[Tue Apr  3 00:33:35 CEST 2018] Installing cron job
_crontab: no crontab for root
crontab: no crontab for root_`

**Comment by danb35** [comment]
> And using crontab -e showed nothing inside the jail.
It doesn't?
```
[root@nextcloud ~]# crontab -l
24 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[root@nextcloud ~]# 
```
> the package is stabler than acme.sh directly from the master branch at github
Stable cuts two ways--it can avoid problems caused by ill-considered changes in the master branch, but it also means it's slow to release bug fixes.  Acme.sh 2.7.5 (the current version packaged) is nearly four months old, and a lot has happened since then--acmev2 compatibility, wildcard support, added DNS APIs, bug fixes...

**Comment by Tim-ofzo** [comment]
It's weird that a few of the commands of the script work as intended on your system, but at mine it doesn't.
Thats also the reason I used `iocage exec ${JAIL_NAME} su -m acme -c "crontab /mnt/configs/acme-crontab"` instead of `iocage exec ${JAIL_NAME} crontab -u acme /mnt/configs/acme-crontab`
But you're right in using the newer version if so much has changed in the meantime. Portsnap package isn't really a better choice since it's just days behind github.

**Comment by danb35** [comment]
> It's weird that a few of the commands of the script work as intended on your system, but at mine it doesn't.

Indeed.  I do get the messages while installing that there's no crontab for root, but I took those to be saying that there wasn't one already--there certainly is one once the script finishes.

**Comment by Tim-ofzo** [comment]
It would be a lot of work, but maybe for the better though: make the script stop when something fails and deliver a useful error message/log.

**Pull request merged**
