### PR TITLE
Direct stdout and stderr to /var/log/caddy.log.

### PR DESCRIPTION
**Pull request by basilhendroff**
More information at https://caddy.community/t/how-to-use-the-expanded-form-of-php-fastcgi/9228/1

### CODE REVIEW

**Comment by danb35** [comment]
Interesting.  Definitely a good move to use the $pidfile variable in the start command (what else was the point of defining it in the first place?).  But I think I like having the Caddy log location configurable, as it was in the v1 rc script.

Can you explain why you've changed `start_cmd` from a one-line definition into a function?

**Comment by basilhendroff** [comment]
> Interesting. Definitely a good move to use the $pidfile variable in the start command (what else was the point of defining it in the first place?). But I think I like having the Caddy log location configurable, as it was in the v1 rc script.
> 
> Can you explain why you've changed `start_cmd` from a one-line definition into a function?

Only because I couldn't get the one-line version working.

**Comment by danb35** [comment]
> Only because I couldn't get the one-line version working

I should probably actually test mine, then.  It **should** work, but...

> I also had the idea that a 'verbose mode' might be a good idea

How do you see this working?  Setting a rc.conf option that would put all the log output back on the console?

**Comment by danb35** [comment]
Thanks for the PR, but took care of this slightly differently.

**Pull request closed without merging**
