### PR TITLE
Update httpd.conf to solve security issue

### PR DESCRIPTION
**Pull request by Jacopx**
Adding line for solving the security issue report in this post: https://help.nextcloud.com/t/strict-transport-security-http-header-hsts/7047 
Solution is referring to the 2nd forum post hint

[I'm not sure is the best place where to write that lines (not so much experience with Apache), but I have check and it's work]

### CODE REVIEW

**Comment by danb35** [comment]
The nextcloud.conf file contains the line for HSTS, but it's commented out.  This is because HSTS can break access to the site if your SSL configuration isn't working quite right (or, perhaps, your Let's Encrypt cert isn't renewing as it should).  But I should probably document that in the README.

**Comment by Jacopx** [comment]
Thanks for the explanations ;)

**Comment by danb35** [comment]
I have now added an explanation to the README; take a look and see if you think it could be improved.

**Comment by Jacopx** [comment]
I think is perfect 👍🏻

**Pull request closed without merging**
